name: Build & Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push backend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/salsabilngh/ids/ids-api:latest
            ghcr.io/salsabilngh/ids/ids-api:${{ github.sha }}

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps & build (pin ajv v6 / keywords v3 + react-scripts + web-vitals)
        working-directory: Frontend
        env:
          CI: "false"   # n’arrête pas le build CRA sur warnings
        run: |
          # Ne PAS supprimer le lockfile si présent (évite les upgrades sauvages)
          # Si pas de lockfile, on fait une install souple
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund || npm install --legacy-peer-deps --no-audit --no-fund
          else
            npm install --legacy-peer-deps --no-audit --no-fund
          fi

          # Corrige le couple versions attendu par webpack/react-scripts
          npm install -D ajv@6 ajv-keywords@3 schema-utils@3 --no-audit --no-fund

          # S’assure que ces 2 packages existent
          npm install react-scripts@5 web-vitals --save --legacy-peer-deps --no-audit --no-fund

          # (filet de sécurité) s’assure que le script build existe
          npm pkg set scripts.build="react-scripts build"

          # Build
          npm run build

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/salsabilngh/ids/frontend:latest
            ghcr.io/salsabilngh/ids/frontend:${{ github.sha }}


