name: Build & Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: |
            ghcr.io/salsabilngh/ids/ids-api:latest
            ghcr.io/salsabilngh/ids/ids-api:${{ github.sha }}

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps & build (add react-scripts + web-vitals)
        working-directory: Frontend
        env:
          CI: "false"   # empêche CRA d'arrêter sur les warnings
        run: |
          rm -rf node_modules package-lock.json
          # installe les dépendances normales
          npm install --legacy-peer-deps --no-audit --no-fund
          # installe les packages manquants
          npm install react-scripts@5 web-vitals --save --legacy-peer-deps --no-audit --no-fund
          # s’assure que le script build est bien défini
          npm pkg set scripts.build="react-scripts build"
          # build du frontend
          npm run build

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/salsabilngh/ids/frontend:latest
            ghcr.io/salsabilngh/ids/frontend:${{ github.sha }}



