name: Build & Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build & Push backend
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: |
            ghcr.io/salsabilngh/ids_ml/ids-api:latest
            ghcr.io/salsabilngh/ids_ml/ids-api:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/salsabilngh/ids_ml/cache:backend
          cache-to: type=registry,ref=ghcr.io/salsabilngh/ids_ml/cache:backend,mode=max

  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install deps & build React
        working-directory: Frontend
        run: |
          npm ci || npm install
          npm run build
      - name: Build & Push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/salsabilngh/ids_ml/frontend:latest
            ghcr.io/salsabilngh/ids_ml/frontend:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/salsabilngh/ids_ml/cache:frontend
          cache-to: type=registry,ref=ghcr.io/salsabilngh/ids_ml/cache:frontend,mode=max
